site_name: Joseph Hansen's Blog
site_description: Joseph Hansen's Blog
site_author: Joseph Hansen
site_url: https://blog.josephhansen.dev

extra:
  cusdis:
    host: https://cusdis.com
    app_id: 44e42f15-0a8f-4529-843f-49768839ef37
    lang: en

theme:
  name: shadcn
  custom_dir: docs/overrides

extra_css:
  - stylesheets/blog-custom.css

hooks:
  - docs/hooks.py

plugins:
  - search
  - pub-meta:
      publish:
        file_default: draft
        file_warn_on_missing: false
        dir_default: published
  - pub-blog:
      slug: blog
      teaser_marker: "<!-- more -->"
      posts_per_page: 10
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: _templates
      backlinks:
        enabled: true
      callouts:
        enabled: true
      links:
        wikilinks_enabled: true
        img_lazy_loading: true
  - link-marker:
      enable_external_link: true
      icon_external_link: "⧉"
      enable_mail: true
      icon_mail: "✉"
  - caption

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - fenced_code
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
